### ISSUE TITLE
Important files of the datasets are missing

### ISSUE THREAD

**Issue by JieQin-AI** [xingzhehe/GANSeg#2]
When I preprocess the datasets of Celeba, cub, and flowers, some of the important files are missing, such as ''list_imsize_celeba.txt'', ''MAFL/celebA_training.txt'', ''train_val_test_split.txt'', etc. Can you provide all these files of datasets?

**Comment by xingzhehe** [comment]
Thanks for pointing it out! 
I originally downloaded these files from various repositories. 
Sorry for the inconvenience! Now I have uploaded them.
